server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
  datasource:
    url: jdbc:mysql://localhost:3307/summary
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  redis:
    data:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}
  jwt:
    secret: ${JWT_SECRET}
google:
  auth:
    url: https://oauth2.googleapis.com
  login:
    url: https://accounts.google.com/o/oauth2/v2/auth?
  redirect:
    url: ${REDIRECT_URL}
  client:
    id: ${GOOGLE_ID}
    pw: ${GOOGLE_PWD}
  mobile:
    id: ${GOOGLE_MOBILE_ID}

cloud:
  aws:
    s3:
      bucket: sseksak
      path:
        user : user
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

openai:
  api:
    key: ${OPENAI_API_KEY}